# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90bad9820c3a242c2fbb243343583cbe16808a1026728c2935758e3f1d3154250a0e5685f27367ca14bd5cd9a982c742b9372f7e51eb2a9064f40dab0c9a139

test:
  secret_key_base: 552abd6cde2260c53c27af3e5dd667081d0d94543f5ea3b25ba2d95cecaa50757d64b57684a4c34e9ff0c4038b2266c8f1bb7422b417d55a68ff08e504c8d226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
